# Generated by Django 3.1.1 on 2020-10-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameResearch', models.CharField(max_length=255)),
                ('NameResearchbase', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('Research_level', models.IntegerField(max_length=255)),
                ('Works', models.IntegerField(max_length=255)),
                ('book', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Phone_number', models.IntegerField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Criterion', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Degree_Certificate', models.CharField(max_length=255)),
                ('test_date', models.DateField(max_length=255)),
                ('Startdate', models.DateField(max_length=255)),
                ('Date_you_can_request_position', models.DateField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='request_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessment_date', models.DateField(max_length=255)),
                ('NameResearchwork', models.CharField(max_length=255)),
                ('Research_base', models.CharField(max_length=255)),
                ('Date', models.DateField(max_length=255)),
                ('Research_level', models.IntegerField(max_length=255)),
                ('Theresult_of_theoperation', models.CharField(max_length=255)),
                ('Criterion', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namestatus', models.CharField(max_length=255)),
            ],
        ),
    ]
